<?php

/*
|--------------------------------------------------------------------------
| AHP indicator registry v2
| Source: data/20260905_AHP_ Indicators_kpq.xlsx (supersedes the July file)
|--------------------------------------------------------------------------
| status:
|   active  - computed per the kpq matrix definition
|   proxy   - the current forms cannot express the indicator exactly; the
|             documented proxy is computed (see note). "Interim" proxies
|             switch to the Labour & Delivery (ld_*) fields once that form
|             is live and `ld.enabled` below is turned on.
|   blocked - not computable until the L&D form provides the source field
| type: count | percent | sum
| no_period: instrument has no date field; the value is all-time.
| Definitions sheet: adolescent = 10-19 years at time of service;
| LTFU = appointment missed by 28 days; age bands 10-14 / 15-19.
*/

return [
    'groups' => [
        ['key' => 'access',  'label' => 'Service access'],
        ['key' => 'hiv',     'label' => 'HIV testing'],
        ['key' => 'art',     'label' => 'ART cascade'],
        ['key' => 'mnch',    'label' => 'ANC & PNC'],
        ['key' => 'fp_prep', 'label' => 'FP & PrEP'],
        ['key' => 'mh',      'label' => 'Mental health & substance use'],
        ['key' => 'sti',     'label' => 'STI'],
        ['key' => 'peer',    'label' => 'Peer & community'],
    ],

    /*
    | Labour & Delivery instrument (announced in the kpq matrix, form not
    | yet live). When data starts arriving AND the choice codes below are
    | confirmed against the real dictionary, set enabled=true: indicators
    | 20-24, 27, 28 then read ld_* instead of their PNCR interim proxies.
    | The codes below are ASSUMPTIONS pending the L&D data dictionary.
    */
    'ld' => [
        'enabled' => false,
        'codes' => [
            'preg_outcome_live' => '1',
            'preg_outcome_stillbirth' => '2',
            'place_institutional' => '1',
            'place_home' => '2',
            'place_bba' => '3',
        ],
    ],

    'indicators' => [
        ['id' => 1,  'code' => 'AHP001', 'key' => 'access_clients',    'group' => 'access',  'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents accessing services',          'definition' => 'Unique adolescents aged 10-19 accessing any adolescent service during the reporting period.', 'variables' => null, 'disaggregation' => ['age', 'sex', 'service_point'], 'note' => null],
        ['id' => 2,  'code' => 'AHP002', 'key' => 'access_first',      'group' => 'access',  'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'First-time adolescent visits',            'definition' => 'Adolescents whose first-ever documented visit falls in the period.', 'variables' => null, 'disaggregation' => ['age', 'sex'], 'note' => null],
        ['id' => 3,  'code' => 'AHP003', 'key' => 'access_repeat',     'group' => 'access',  'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Repeat adolescent visits',                'definition' => 'Follow-up visits in the period, excluding each client\'s first-ever visit.', 'variables' => null, 'disaggregation' => [], 'note' => null],

        ['id' => 4,  'code' => 'AHP004', 'key' => 'hiv_tested',        'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents tested for HIV',              'definition' => 'Unique adolescents with a documented HIV test in the HTS register during the period.', 'variables' => 'HTS-0 (hts_tested)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'HTS register only, per the kpq matrix (previous draft unioned STI/PrEP/ANC tests).'],
        ['id' => 5,  'code' => 'AHP005', 'key' => 'hiv_positive',      'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents testing HIV positive',        'definition' => 'Unique adolescents with a positive HTS result during the period.', 'variables' => 'HTS-2 (hts_hiv_result)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 6,  'code' => 'AHP006', 'key' => 'hiv_positivity',    'group' => 'hiv',     'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'HIV positivity rate',                     'definition' => 'AHP005 / AHP004 x 100.', 'variables' => 'AHP005 / AHP004', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 46, 'code' => 'AHP004a', 'key' => 'hiv_tested_all',   'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Tested for HIV — all entry points',       'definition' => 'Unique adolescents with a documented HIV test in any register (HTS, STI, PrEP or ANC) during the period.', 'variables' => 'hts_tested, sti_hiv_test, prep_hiv_test, anc_hiv_test_results, artr_first_hiv_test', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Supplementary indicator: the official AHP004 counts the HTS register only. Includes the OI/ART register\'s first confirmed test date.'],
        ['id' => 47, 'code' => 'AHP005a', 'key' => 'hiv_positive_all', 'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'HIV positive — all entry points',         'definition' => 'Unique adolescents with a positive HIV result in any register during the period.', 'variables' => 'hts_hiv_result, sti_hiv_test_result, prep_hiv_test_results, anc_hiv_test_results, artr_first_hiv_test', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Supplementary indicator: the official AHP005 counts the HTS register only. A confirmed first test in the OI/ART register counts as positive.'],
        ['id' => 48, 'code' => 'AHP006a', 'key' => 'hiv_positivity_all', 'group' => 'hiv',   'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'HIV positivity rate — all entry points',  'definition' => 'AHP005a / AHP004a x 100.', 'variables' => 'AHP005a / AHP004a', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Supplementary indicator complementing the HTS-only official rate.'],

        ['id' => 7,  'code' => 'AHP007', 'key' => 'art_initiated',     'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents initiated on ART',            'definition' => 'Unique adolescents with ART initiation documented in the HTS register during the period.', 'variables' => 'HTS-3 (hts_art_init)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'HTS register cannot distinguish re-initiations or transfer-ins already on ART; those exclusions are not machine-checkable.'],
        ['id' => 8,  'code' => 'AHP008', 'key' => 'art_current',       'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents currently on ART',            'definition' => 'Latest ART visit on/before period end; not dead/TO/LTFU/opted-out; next appointment under 28 days overdue.', 'variables' => 'ART-22 (art_next_review_date), ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 9,  'code' => 'AHP009', 'key' => 'art_retention',     'group' => 'art',     'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => '12-month ART retention rate',             'definition' => 'Of adolescents initiated 12 months before the period (per AHP007), share with an ART visit 9-15 months after initiation and not recorded dead/TO.', 'variables' => null, 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Provisional cohort logic pending stakeholder validation.'],
        ['id' => 10, 'code' => 'AHP010', 'key' => 'art_ltfu',          'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Adolescents lost to follow-up',           'definition' => 'Next ART review date missed by 28+ days at period end; not recorded dead or transferred out.', 'variables' => 'ART-22 (art_next_review_date), ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 11, 'code' => 'AHP011', 'key' => 'art_ti',            'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents transferred in',              'definition' => 'Unique adolescents with a documented referral into HIV care during the period.', 'variables' => 'ARTR-2 (artr_referred)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'The kpq matrix maps transfer-in to the OI/ART register\'s "referred" field.'],
        ['id' => 12, 'code' => 'AHP012', 'key' => 'art_to',            'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents transferred out',             'definition' => 'Final outcome "Transfer Out" recorded in the period.', 'variables' => 'ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 13, 'code' => 'AHP013', 'key' => 'art_died',          'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'HIV-positive adolescents who died',       'definition' => 'Final outcome "Died" recorded in the period.', 'variables' => 'ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 14, 'code' => 'AHP014', 'key' => 'art_vl_tested',     'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents with viral load test',        'definition' => 'Unique adolescents with a VL sample collected in the period.', 'variables' => 'ART-19a (art_viral_load)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 15, 'code' => 'AHP015', 'key' => 'art_vl_tnd',        'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Adolescents with TND result',             'definition' => 'VL result recorded as target not detected in the period.', 'variables' => 'ART-19c (art_vl_detected)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 16, 'code' => 'AHP016', 'key' => 'art_vl_suppressed', 'group' => 'art',     'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'Viral load suppression (<1000)',          'definition' => '(TND + numeric VL under 1000) / VL tested x 100.', 'variables' => '(ART-19c + ART-19d) / ART-19a', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 17, 'code' => 'AHP017', 'key' => 'art_vl_high',       'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Viral load 1000+ copies/mL',              'definition' => 'Numeric VL result of 1000 or more in the period.', 'variables' => 'ART-19d (art_vl_result)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],

        ['id' => 18, 'code' => 'AHP018', 'key' => 'anc_new',           'group' => 'mnch',    'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'New ANC adolescent bookings',             'definition' => 'Unique adolescents with a first ANC booking in the period.', 'variables' => 'ANCR-3 (ancr_first_booking)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 19, 'code' => 'AHP019', 'key' => 'anc_8plus',         'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'Completed 8+ ANC contacts',               'definition' => 'Of adolescent deliveries in the period, share whose recorded ANC contacts reached 8.', 'variables' => null, 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Delivery-cohort proxy: no pregnancy ID exists.'],
        ['id' => 20, 'code' => 'AHP020', 'key' => 'births_inst',       'group' => 'mnch',    'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Institutional live births',               'definition' => 'Live births in a health facility.', 'variables' => 'LD-1 (ld_preg_outcome)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: institutional mother-baby registrations until the Labour & Delivery form is live.'],
        ['id' => 21, 'code' => 'AHP021', 'key' => 'births_home',       'group' => 'mnch',    'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Home deliveries (incl. BBA)',             'definition' => 'Deliveries outside a health facility (home + BBA, per the kpq matrix).', 'variables' => 'LD-3 (ld_delivery_place_2)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNCR place of delivery until the L&D form is live.'],
        ['id' => 22, 'code' => 'AHP022', 'key' => 'stillbirths',       'group' => 'mnch',    'level' => 'Outcome', 'type' => 'count',   'status' => 'blocked', 'label' => 'Institutional stillbirths',              'definition' => 'Stillbirths in a health facility.', 'variables' => 'LD-1 (ld_preg_outcome)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'No current form captures birth outcome; available once the L&D form is live.'],
        ['id' => 23, 'code' => 'AHP023', 'key' => 'neonatal_deaths',   'group' => 'mnch',    'level' => 'Outcome', 'type' => 'count',   'status' => 'proxy',  'label' => 'Early neonatal deaths',                   'definition' => 'Live-born infants dying within 7 days of birth.', 'variables' => 'LD-4 (ld_newborn_die)', 'disaggregation' => ['facility', 'district'], 'note' => 'Interim: baby follow-up "infant dead" within 7 days of PNCR birth date.'],
        ['id' => 24, 'code' => 'AHP024', 'key' => 'maternal_deaths',   'group' => 'mnch',    'level' => 'Outcome', 'type' => 'count',   'status' => 'proxy',  'label' => 'Maternal deaths',                         'definition' => 'Maternal deaths among adolescent mothers.', 'variables' => 'LD-5 (ld_mother_die)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: mother follow-up outcome "Dead" until the L&D form is live.'],
        ['id' => 25, 'code' => 'AHP025', 'key' => 'pnc_72h',           'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'PNC visit within 72 hrs',                 'definition' => 'Deliveries in the period with a mother PNC visit within 3 days of birth.', 'variables' => null, 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNCR + mother follow-up dates.'],
        ['id' => 26, 'code' => 'AHP026', 'key' => 'anc_first_tested',  'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'HIV status documented at first ANC',      'definition' => 'First bookings with documented (non-unknown) prior HIV status / new bookings x 100.', 'variables' => 'ANCR-15B (ancr_hiv_prior) / ANCR-3 (ancr_first_booking)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 27, 'code' => 'AHP027', 'key' => 'bf_retest',         'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'HIV retest while breastfeeding',          'definition' => 'HIV-negative mothers in PNC follow-up retested in the period.', 'variables' => 'LD-9 (ld_hiv_test_bf) / LD-6 (ld_breastfeeding)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNC mother follow-up fields until the L&D form is live.'],
        ['id' => 28, 'code' => 'AHP028', 'key' => 'art_at_delivery',   'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'HIV-positive mothers on ART at delivery', 'definition' => 'HIV-positive deliveries with mother on ART / HIV-positive deliveries x 100.', 'variables' => 'LD-12 (ld_recieve_art) / LD-8 (ld_hiv_status)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNCR HIV/ART fields until the L&D form is live.'],

        ['id' => 29, 'code' => 'AHP029', 'key' => 'fp_new',            'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'New FP users',                            'definition' => 'Unique adolescents with FP category "New user" in the period.', 'variables' => 'FP-1 (fp_client_category)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 30, 'code' => 'AHP030', 'key' => 'fp_repeat',         'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Repeat FP users',                         'definition' => 'Unique adolescents with FP category "Repeat user" in the period.', 'variables' => 'FP-1 (fp_client_category)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 31, 'code' => 'AHP031', 'key' => 'prep_screened',     'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for PrEP eligibility',           'definition' => 'Unique adolescents screened for PrEP eligibility in the period.', 'variables' => 'PrEPr-2 (prepr_screened)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 32, 'code' => 'AHP032', 'key' => 'prep_initiated',    'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Initiated on PrEP',                       'definition' => 'Unique adolescents newly initiated on PrEP in the period.', 'variables' => 'PrEPr-4 (prepr_visit_status)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 33, 'code' => 'AHP033', 'key' => 'prep_continuing',   'group' => 'fp_prep', 'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Continuing on PrEP',                      'definition' => 'Unique adolescents recorded as continuing or newly initiated on PrEP in the period.', 'variables' => 'PrEPr-4 (prepr_visit_status)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Per the kpq matrix, continuing includes newly initiated.'],
        ['id' => 34, 'code' => 'AHP034', 'key' => 'prep_discontinued', 'group' => 'fp_prep', 'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Discontinued from PrEP',                  'definition' => 'Unique adolescents recorded as discontinued on PrEP in the period.', 'variables' => 'PrEPr-4 (prepr_visit_status)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],

        ['id' => 35, 'code' => 'AHP035', 'key' => 'mh_screened',       'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for mental health',              'definition' => 'Unique adolescents with a completed MH screening.', 'variables' => 'MH-0 (mh_screening_tools)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 36, 'code' => 'AHP036', 'key' => 'mh_positive',       'group' => 'mh',      'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Screening MH positive',                   'definition' => 'Unique adolescents with a positive MH screening result.', 'variables' => 'MH-1 (mh_screening_results)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 37, 'code' => 'AHP037', 'key' => 'mh_managed',        'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Referred/managed for MH',                 'definition' => 'Unique adolescents referred and/or managed after MH screening.', 'variables' => 'MH-2 (mh_management_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 38, 'code' => 'AHP038', 'key' => 'su_screened',       'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for substance use',              'definition' => 'MH screenings in which the substance-use question was answered.', 'variables' => 'MH-0 (mh_screening_tools)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Substance screening is a component of the MH tool, per the kpq matrix.', 'no_period' => true],
        ['id' => 39, 'code' => 'AHP039', 'key' => 'su_positive',       'group' => 'mh',      'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Screening positive for substance use',    'definition' => 'Unique adolescents with substance use identified.', 'variables' => 'MH-3 (mh_substance_identified)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 40, 'code' => 'AHP040', 'key' => 'su_managed',        'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Referred/managed for substance use',      'definition' => 'Substance-positive adolescents with any MH management outcome.', 'variables' => 'N/A in matrix', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'The kpq matrix lists no definition (N/A); documented proxy applied.', 'no_period' => true],

        ['id' => 41, 'code' => 'AHP041', 'key' => 'sti_screened',      'group' => 'sti',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for STIs',                       'definition' => 'Unique adolescents who accessed the STI register in the period.', 'variables' => 'STI-S (sti_access)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 42, 'code' => 'AHP042', 'key' => 'sti_treated',       'group' => 'sti',     'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Treated for STIs',                        'definition' => 'Unique adolescents recorded as treated in the STI register in the period.', 'variables' => 'N/A in matrix', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'The kpq matrix lists no definition (N/A); documented proxy (sti_patient_treated) applied.'],

        ['id' => 43, 'code' => 'AHP043', 'key' => 'peer_sessions',     'group' => 'peer',    'level' => 'Output',  'type' => 'sum',     'status' => 'active', 'label' => 'Peer-led sessions conducted',             'definition' => 'Sum of peer-led sessions recorded in the period.', 'variables' => null, 'disaggregation' => ['facility', 'district'], 'note' => null],
        ['id' => 44, 'code' => 'AHP044', 'key' => 'peer_reached',      'group' => 'peer',    'level' => 'Output',  'type' => 'sum',     'status' => 'active', 'label' => 'Adolescents reached via peer activities', 'definition' => 'Sum of adolescents recorded as reached in the period.', 'variables' => null, 'disaggregation' => ['facility', 'district'], 'note' => null],
        ['id' => 45, 'code' => 'AHP045', 'key' => 'support_groups',    'group' => 'peer',    'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Adolescent support groups conducted',     'definition' => 'Register entries recording a support group conducted in the period.', 'variables' => null, 'disaggregation' => ['facility', 'district'], 'note' => 'Only a yes/no field exists, no meeting count.'],
    ],

    /*
    | "How we calculated this" - plain-language method per indicator for the
    | M&E accordion and the Excel Definitions sheet. The common rules below
    | apply to every indicator and are shown once, not repeated.
    */
    'method_common' => 'Common rules: a patient is identified by the REDCap record, which is shared across projects 76 (FCH), 78 (OI/ART) and 79 (OPD), so "unique adolescents" are counted once with COUNT(DISTINCT record) however many services or projects they appear in. Service-specific forms are read only from their home project (FCH forms from 76, OI/ART forms from 78, OPD from 79); shared instruments (STI, PrEP, HTS, MH, health education, counselling, peer support) are combined across all three projects and deduplicated. Adolescent = aged 10-19 at the indicator\'s reference date, computed from demog_dateofbirth. Facility, district and sex come from demog_facility, demog_district and demog_gender.',

    'methods' => [
        'access_clients' => 'Collects every dated encounter from all instruments using their visit-date fields (sti_visit_date, fp_date, ancr_date, anc_date, pncr_date, pncm_visit_date, pncb_visit_date, prepr_date, prep_visit_date, artr_registration_date, art_review_date, hts_hiv_date, pls_date, opd_date). Clients with at least one encounter dated in the period, aged 10-19 at that visit, are counted once.',
        'access_first' => 'Takes each client\'s earliest encounter date across all instruments (all time, same date fields as AHP001). The client is counted when that first-ever date falls inside the reporting period and they are 10-19 at that date.',
        'access_repeat' => 'Counts encounter rows dated in the period whose date is after the client\'s first-ever encounter date; the first visit itself is excluded. This counts visits, not unique clients.',
        'hiv_tested' => 'HTS register only: rows with hts_tested = Yes, dated by hts_hiv_date. Unique clients aged 10-19 at the test date.',
        'hiv_positive' => 'HTS register only: hts_tested = Yes AND hts_hiv_result = P (positive), dated by hts_hiv_date. Unique clients.',
        'hiv_positivity' => 'AHP005 divided by AHP004 x 100, computed inside the same period, age and location filters.',
        'hiv_tested_all' => 'Union of every documented testing entry point: hts_tested = Yes (hts_hiv_date), sti_hiv_test = Yes (sti_visit_date), prep_hiv_test = Yes (prep_visit_date), anc_hiv_test_results in {P, N} (anc_date), and a dated artr_first_hiv_test in the OI/ART register. One count per client per period regardless of how many places they tested.',
        'hiv_positive_all' => 'Same union as AHP004a, keeping only positive results (result = P in HTS/STI/PrEP/ANC; any dated artr_first_hiv_test counts as positive because it is the confirmed test that led to HIV-care enrolment).',
        'hiv_positivity_all' => 'AHP005a divided by AHP004a x 100.',
        'art_initiated' => 'HTS register: hts_art_init = Y. The earliest such entry per client (dated hts_hiv_date) defines the initiation date; counted when that date falls in the period.',
        'art_current' => 'OI/ART follow-ups (project 78): take each client\'s latest visit (art_review_date) on or before the period end. Counted when art_final_outcome is not LTFU/Transferred out/Died/Opted out AND art_next_review_date is less than 28 days overdue at the period end. Age is taken at the period end.',
        'art_retention' => 'Cohort: clients whose ART initiation (per AHP007) fell 12 months before the reporting period. Retained: the client has an OI/ART visit (art_review_date) 9-15 months after initiation and no Died/Transferred-out outcome within 12 months of initiation.',
        'art_ltfu' => 'OI/ART follow-ups: latest visit per client on or before the period end, where art_next_review_date is 28 or more days overdue at the period end and art_final_outcome is not Died or Transferred out. Age at period end.',
        'art_ti' => 'OI/ART initial register (project 78): artr_referred = Yes, dated by artr_registration_date. Unique clients. (The kpq matrix maps "transferred in" to this referral field.)',
        'art_to' => 'OI/ART follow-ups: a visit dated in the period (art_review_date) with art_final_outcome = Transfer Out. Unique clients.',
        'art_died' => 'OI/ART follow-ups: a visit dated in the period with art_final_outcome = Died. Unique clients.',
        'art_vl_tested' => 'OI/ART follow-ups: art_viral_load = Yes (sample collected), dated by art_vl_collect_date, falling back to the visit date when the collection date is blank. Unique clients.',
        'art_vl_tnd' => 'As AHP014, additionally requiring art_vl_detected = No (target not detected).',
        'art_vl_suppressed' => 'Numerator: VL-tested clients whose result is TND (art_vl_detected = No) or a numeric art_vl_result under 1000 copies/mL. Denominator: AHP014. Non-numeric results other than TND are excluded from the numerator.',
        'art_vl_high' => 'OI/ART follow-ups: numeric art_vl_result of 1000 or more, dated as in AHP014. Unique clients.',
        'anc_new' => 'ANC initial register (project 76): ancr_first_booking = Yes, dated by ancr_date. Unique clients aged 10-19 at booking.',
        'anc_8plus' => 'Denominator: mother-baby pair registrations (pncr_date in the period) - i.e. completed pregnancies. Numerator: those whose highest recorded ANC contact number (ancr_contact_number or anc_contact_number, any time) reached 8. Proxy because no pregnancy ID exists to group visits per pregnancy.',
        'births_inst' => 'Mother-baby pair register (per baby): pncr_place_of_delivery = Institutional, dated by pncr_date. Counted per registration (one per baby). Interim proxy: the register only enrols live pairs, so this approximates live births until the Labour & Delivery form (ld_preg_outcome) is live.',
        'births_home' => 'Mother-baby pair register: pncr_place_of_delivery = Home or BBA (born before arrival), dated by pncr_date, counted per registration. BBA counts as non-institutional per the kpq matrix.',
        'stillbirths' => 'Not computable: no current form records the birth outcome. Will be computed from ld_preg_outcome = Stillbirth once the Labour & Delivery form is live.',
        'neonatal_deaths' => 'Baby follow-ups: pncb_infant_follow_ups = Infant dead, where pncb_visit_date is within 7 days of the baby\'s birth date (pncr_date_of_birth, joined at record level), dated by the follow-up visit.',
        'maternal_deaths' => 'Mother follow-ups: pncm_mother_follow_up = Dead, dated by pncm_visit_date. Unique clients.',
        'pnc_72h' => 'Denominator: mother-baby registrations dated in the period. Numerator: those with a mother follow-up visit (pncm_visit_date) within 3 days of the birth date (pncr_date_of_birth).',
        'anc_first_tested' => 'Denominator: first bookings (ancr_first_booking = Yes) in the period. Numerator: those with ancr_hiv_prior documented as Negative or Positive (Unknown fails). Proxy for "tested at first contact" - the register records status, not the test event.',
        'bf_retest' => 'Denominator: mothers registered HIV-negative (pncr_hiv_status_post = N) with a mother follow-up visit in the period. Numerator: those with pncm_hiv_tested = Yes in the period. Breastfeeding status is approximated (it lives on the baby form) until the L&D form provides ld_breastfeeding.',
        'art_at_delivery' => 'Mother-baby registrations with pncr_hiv_status_post = P (denominator); numerator additionally requires pncr_hiv_status_art = Yes. Dated by pncr_date.',
        'fp_new' => 'Family planning (project 76): fp_client_category = N (new user), dated by fp_date. Unique clients.',
        'fp_repeat' => 'Family planning: fp_client_category = R (repeat user), dated by fp_date. Unique clients.',
        'prep_screened' => 'PrEP initial register (all projects, deduplicated): prepr_screened = Yes, dated by prepr_date. Unique clients.',
        'prep_initiated' => 'PrEP initial register: prepr_visit_status = N (newly initiated) or prepr_prep_initiate = Yes, dated by prepr_prep_start_date falling back to prepr_date. Unique clients.',
        'prep_continuing' => 'PrEP initial register: prepr_visit_status = C or N (continuing includes newly initiated per the kpq matrix), dated by prepr_date. Unique clients.',
        'prep_discontinued' => 'PrEP initial register: prepr_visit_status = D, dated by prepr_date. Unique clients.',
        'mh_screened' => 'Mental health instrument (all projects, deduplicated): mh_screening_tools = Yes. The instrument has no date field, so the value is all-time and age is taken at the period end.',
        'mh_positive' => 'Mental health instrument: mh_screening_results = P (positive). All-time; unique clients.',
        'mh_managed' => 'Mental health instrument: mh_management_outcome = Referred, Managed or Both. All-time; unique clients.',
        'su_screened' => 'Mental health instrument: mh_screening_tools = Yes with the substance question (mh_substance_identified) answered - substance screening is a component of the MH tool per the kpq matrix. All-time.',
        'su_positive' => 'Mental health instrument: mh_substance_identified = Yes. All-time; unique clients.',
        'su_managed' => 'Mental health instrument: mh_substance_identified = Yes AND mh_management_outcome = Referred/Managed/Both. Proxy - the outcome field covers the whole screening, not the substance finding specifically. All-time.',
        'sti_screened' => 'STI register (all projects, deduplicated): any register visit dated by sti_visit_date, falling back to sti_date. Unique clients.',
        'sti_treated' => 'STI register: sti_patient_treated = Yes, dated as in AHP041. Unique clients. Proxy - the kpq matrix lists no definition for this indicator.',
        'peer_sessions' => 'Peer support register (deduplicated across projects by record, date and instance): sum of pls_number where pls_session_conducted = Yes, dated by pls_date.',
        'peer_reached' => 'Peer support register: sum of pls_ado_number where pls_session_conducted = Yes, dated by pls_date.',
        'support_groups' => 'Peer support register: count of entries with pls_support_conducted = Yes, dated by pls_date. Proxy - only a yes/no exists, so multiple meetings between entries are undercounted.',
    ],
];
