<?php

/*
|--------------------------------------------------------------------------
| AHP indicator registry v2
| Source: data/20260905_AHP_ Indicators_kpq.xlsx (supersedes the July file)
|--------------------------------------------------------------------------
| status:
|   active  - computed per the kpq matrix definition
|   proxy   - the current forms cannot express the indicator exactly; the
|             documented proxy is computed (see note). "Interim" proxies
|             switch to the Labour & Delivery (ld_*) fields once that form
|             is live and `ld.enabled` below is turned on.
|   blocked - not computable until the L&D form provides the source field
| type: count | percent | sum
| no_period: instrument has no date field; the value is all-time.
| Definitions sheet: adolescent = 10-19 years at time of service;
| LTFU = appointment missed by 28 days; age bands 10-14 / 15-19.
*/

return [
    'groups' => [
        ['key' => 'access',  'label' => 'Service access'],
        ['key' => 'hiv',     'label' => 'HIV testing'],
        ['key' => 'art',     'label' => 'ART cascade'],
        ['key' => 'mnch',    'label' => 'ANC & PNC'],
        ['key' => 'fp_prep', 'label' => 'FP & PrEP'],
        ['key' => 'mh',      'label' => 'Mental health & substance use'],
        ['key' => 'sti',     'label' => 'STI'],
        ['key' => 'peer',    'label' => 'Peer & community'],
    ],

    /*
    | Labour & Delivery instrument (announced in the kpq matrix, form not
    | yet live). When data starts arriving AND the choice codes below are
    | confirmed against the real dictionary, set enabled=true: indicators
    | 20-24, 27, 28 then read ld_* instead of their PNCR interim proxies.
    | The codes below are ASSUMPTIONS pending the L&D data dictionary.
    */
    'ld' => [
        'enabled' => false,
        'codes' => [
            'preg_outcome_live' => '1',
            'preg_outcome_stillbirth' => '2',
            'place_institutional' => '1',
            'place_home' => '2',
            'place_bba' => '3',
        ],
    ],

    'indicators' => [
        ['id' => 1,  'code' => 'AHP001', 'key' => 'access_clients',    'group' => 'access',  'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents accessing services',          'definition' => 'Unique adolescents aged 10-19 accessing any adolescent service during the reporting period.', 'variables' => null, 'disaggregation' => ['age', 'sex', 'service_point'], 'note' => null],
        ['id' => 2,  'code' => 'AHP002', 'key' => 'access_first',      'group' => 'access',  'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'First-time adolescent visits',            'definition' => 'Adolescents whose first-ever documented visit falls in the period.', 'variables' => null, 'disaggregation' => ['age', 'sex'], 'note' => null],
        ['id' => 3,  'code' => 'AHP003', 'key' => 'access_repeat',     'group' => 'access',  'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Repeat adolescent visits',                'definition' => 'Follow-up visits in the period, excluding each client\'s first-ever visit.', 'variables' => null, 'disaggregation' => [], 'note' => null],

        ['id' => 4,  'code' => 'AHP004', 'key' => 'hiv_tested',        'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents tested for HIV',              'definition' => 'Unique adolescents with a documented HIV test in the HTS register during the period.', 'variables' => 'HTS-0 (hts_tested)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'HTS register only, per the kpq matrix (previous draft unioned STI/PrEP/ANC tests).'],
        ['id' => 5,  'code' => 'AHP005', 'key' => 'hiv_positive',      'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents testing HIV positive',        'definition' => 'Unique adolescents with a positive HTS result during the period.', 'variables' => 'HTS-2 (hts_hiv_result)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 6,  'code' => 'AHP006', 'key' => 'hiv_positivity',    'group' => 'hiv',     'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'HIV positivity rate',                     'definition' => 'AHP005 / AHP004 x 100.', 'variables' => 'AHP005 / AHP004', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 46, 'code' => 'AHP004a', 'key' => 'hiv_tested_all',   'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Tested for HIV — all entry points',       'definition' => 'Unique adolescents with a documented HIV test in any register (HTS, STI, PrEP or ANC) during the period.', 'variables' => 'hts_tested, sti_hiv_test, prep_hiv_test, anc_hiv_test_results, artr_first_hiv_test', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Supplementary indicator: the official AHP004 counts the HTS register only. Includes the OI/ART register\'s first confirmed test date.'],
        ['id' => 47, 'code' => 'AHP005a', 'key' => 'hiv_positive_all', 'group' => 'hiv',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'HIV positive — all entry points',         'definition' => 'Unique adolescents with a positive HIV result in any register during the period.', 'variables' => 'hts_hiv_result, sti_hiv_test_result, prep_hiv_test_results, anc_hiv_test_results, artr_first_hiv_test', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Supplementary indicator: the official AHP005 counts the HTS register only. A confirmed first test in the OI/ART register counts as positive.'],
        ['id' => 48, 'code' => 'AHP006a', 'key' => 'hiv_positivity_all', 'group' => 'hiv',   'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'HIV positivity rate — all entry points',  'definition' => 'AHP005a / AHP004a x 100.', 'variables' => 'AHP005a / AHP004a', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Supplementary indicator complementing the HTS-only official rate.'],

        ['id' => 7,  'code' => 'AHP007', 'key' => 'art_initiated',     'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents initiated on ART',            'definition' => 'Unique adolescents with ART initiation documented in the HTS register during the period.', 'variables' => 'HTS-3 (hts_art_init)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'HTS register cannot distinguish re-initiations or transfer-ins already on ART; those exclusions are not machine-checkable.'],
        ['id' => 8,  'code' => 'AHP008', 'key' => 'art_current',       'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents currently on ART',            'definition' => 'Latest ART visit on/before period end; not dead/TO/LTFU/opted-out; next appointment under 28 days overdue.', 'variables' => 'ART-22 (art_next_review_date), ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 9,  'code' => 'AHP009', 'key' => 'art_retention',     'group' => 'art',     'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => '12-month ART retention rate',             'definition' => 'Of adolescents initiated 12 months before the period (per AHP007), share with an ART visit 9-15 months after initiation and not recorded dead/TO.', 'variables' => null, 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Provisional cohort logic pending stakeholder validation.'],
        ['id' => 10, 'code' => 'AHP010', 'key' => 'art_ltfu',          'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Adolescents lost to follow-up',           'definition' => 'Next ART review date missed by 28+ days at period end; not recorded dead or transferred out.', 'variables' => 'ART-22 (art_next_review_date), ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 11, 'code' => 'AHP011', 'key' => 'art_ti',            'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents transferred in',              'definition' => 'Unique adolescents with a documented referral into HIV care during the period.', 'variables' => 'ARTR-2 (artr_referred)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'The kpq matrix maps transfer-in to the OI/ART register\'s "referred" field.'],
        ['id' => 12, 'code' => 'AHP012', 'key' => 'art_to',            'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents transferred out',             'definition' => 'Final outcome "Transfer Out" recorded in the period.', 'variables' => 'ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 13, 'code' => 'AHP013', 'key' => 'art_died',          'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'HIV-positive adolescents who died',       'definition' => 'Final outcome "Died" recorded in the period.', 'variables' => 'ART-24 (art_final_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 14, 'code' => 'AHP014', 'key' => 'art_vl_tested',     'group' => 'art',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Adolescents with viral load test',        'definition' => 'Unique adolescents with a VL sample collected in the period.', 'variables' => 'ART-19a (art_viral_load)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 15, 'code' => 'AHP015', 'key' => 'art_vl_tnd',        'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Adolescents with TND result',             'definition' => 'VL result recorded as target not detected in the period.', 'variables' => 'ART-19c (art_vl_detected)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 16, 'code' => 'AHP016', 'key' => 'art_vl_suppressed', 'group' => 'art',     'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'Viral load suppression (<1000)',          'definition' => '(TND + numeric VL under 1000) / VL tested x 100.', 'variables' => '(ART-19c + ART-19d) / ART-19a', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 17, 'code' => 'AHP017', 'key' => 'art_vl_high',       'group' => 'art',     'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Viral load 1000+ copies/mL',              'definition' => 'Numeric VL result of 1000 or more in the period.', 'variables' => 'ART-19d (art_vl_result)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],

        ['id' => 18, 'code' => 'AHP018', 'key' => 'anc_new',           'group' => 'mnch',    'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'New ANC adolescent bookings',             'definition' => 'Unique adolescents with a first ANC booking in the period.', 'variables' => 'ANCR-3 (ancr_first_booking)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 19, 'code' => 'AHP019', 'key' => 'anc_8plus',         'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'Completed 8+ ANC contacts',               'definition' => 'Of adolescent deliveries in the period, share whose recorded ANC contacts reached 8.', 'variables' => null, 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Delivery-cohort proxy: no pregnancy ID exists.'],
        ['id' => 20, 'code' => 'AHP020', 'key' => 'births_inst',       'group' => 'mnch',    'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Institutional live births',               'definition' => 'Live births in a health facility.', 'variables' => 'LD-1 (ld_preg_outcome)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: institutional mother-baby registrations until the Labour & Delivery form is live.'],
        ['id' => 21, 'code' => 'AHP021', 'key' => 'births_home',       'group' => 'mnch',    'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Home deliveries (incl. BBA)',             'definition' => 'Deliveries outside a health facility (home + BBA, per the kpq matrix).', 'variables' => 'LD-3 (ld_delivery_place_2)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNCR place of delivery until the L&D form is live.'],
        ['id' => 22, 'code' => 'AHP022', 'key' => 'stillbirths',       'group' => 'mnch',    'level' => 'Outcome', 'type' => 'count',   'status' => 'blocked', 'label' => 'Institutional stillbirths',              'definition' => 'Stillbirths in a health facility.', 'variables' => 'LD-1 (ld_preg_outcome)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'No current form captures birth outcome; available once the L&D form is live.'],
        ['id' => 23, 'code' => 'AHP023', 'key' => 'neonatal_deaths',   'group' => 'mnch',    'level' => 'Outcome', 'type' => 'count',   'status' => 'proxy',  'label' => 'Early neonatal deaths',                   'definition' => 'Live-born infants dying within 7 days of birth.', 'variables' => 'LD-4 (ld_newborn_die)', 'disaggregation' => ['facility', 'district'], 'note' => 'Interim: baby follow-up "infant dead" within 7 days of PNCR birth date.'],
        ['id' => 24, 'code' => 'AHP024', 'key' => 'maternal_deaths',   'group' => 'mnch',    'level' => 'Outcome', 'type' => 'count',   'status' => 'proxy',  'label' => 'Maternal deaths',                         'definition' => 'Maternal deaths among adolescent mothers.', 'variables' => 'LD-5 (ld_mother_die)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: mother follow-up outcome "Dead" until the L&D form is live.'],
        ['id' => 25, 'code' => 'AHP025', 'key' => 'pnc_72h',           'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'PNC visit within 72 hrs',                 'definition' => 'Deliveries in the period with a mother PNC visit within 3 days of birth.', 'variables' => null, 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNCR + mother follow-up dates.'],
        ['id' => 26, 'code' => 'AHP026', 'key' => 'anc_first_tested',  'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'active', 'label' => 'HIV status documented at first ANC',      'definition' => 'First bookings with documented (non-unknown) prior HIV status / new bookings x 100.', 'variables' => 'ANCR-15B (ancr_hiv_prior) / ANCR-3 (ancr_first_booking)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 27, 'code' => 'AHP027', 'key' => 'bf_retest',         'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'HIV retest while breastfeeding',          'definition' => 'HIV-negative mothers in PNC follow-up retested in the period.', 'variables' => 'LD-9 (ld_hiv_test_bf) / LD-6 (ld_breastfeeding)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNC mother follow-up fields until the L&D form is live.'],
        ['id' => 28, 'code' => 'AHP028', 'key' => 'art_at_delivery',   'group' => 'mnch',    'level' => 'Outcome', 'type' => 'percent', 'status' => 'proxy',  'label' => 'HIV-positive mothers on ART at delivery', 'definition' => 'HIV-positive deliveries with mother on ART / HIV-positive deliveries x 100.', 'variables' => 'LD-12 (ld_recieve_art) / LD-8 (ld_hiv_status)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => 'Interim: PNCR HIV/ART fields until the L&D form is live.'],

        ['id' => 29, 'code' => 'AHP029', 'key' => 'fp_new',            'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'New FP users',                            'definition' => 'Unique adolescents with FP category "New user" in the period.', 'variables' => 'FP-1 (fp_client_category)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 30, 'code' => 'AHP030', 'key' => 'fp_repeat',         'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Repeat FP users',                         'definition' => 'Unique adolescents with FP category "Repeat user" in the period.', 'variables' => 'FP-1 (fp_client_category)', 'disaggregation' => ['age', 'facility', 'district'], 'note' => null],
        ['id' => 31, 'code' => 'AHP031', 'key' => 'prep_screened',     'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for PrEP eligibility',           'definition' => 'Unique adolescents screened for PrEP eligibility in the period.', 'variables' => 'PrEPr-2 (prepr_screened)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 32, 'code' => 'AHP032', 'key' => 'prep_initiated',    'group' => 'fp_prep', 'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Initiated on PrEP',                       'definition' => 'Unique adolescents newly initiated on PrEP in the period.', 'variables' => 'PrEPr-4 (prepr_visit_status)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 33, 'code' => 'AHP033', 'key' => 'prep_continuing',   'group' => 'fp_prep', 'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Continuing on PrEP',                      'definition' => 'Unique adolescents recorded as continuing or newly initiated on PrEP in the period.', 'variables' => 'PrEPr-4 (prepr_visit_status)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Per the kpq matrix, continuing includes newly initiated.'],
        ['id' => 34, 'code' => 'AHP034', 'key' => 'prep_discontinued', 'group' => 'fp_prep', 'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Discontinued from PrEP',                  'definition' => 'Unique adolescents recorded as discontinued on PrEP in the period.', 'variables' => 'PrEPr-4 (prepr_visit_status)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],

        ['id' => 35, 'code' => 'AHP035', 'key' => 'mh_screened',       'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for mental health',              'definition' => 'Unique adolescents with a completed MH screening.', 'variables' => 'MH-0 (mh_screening_tools)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 36, 'code' => 'AHP036', 'key' => 'mh_positive',       'group' => 'mh',      'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Screening MH positive',                   'definition' => 'Unique adolescents with a positive MH screening result.', 'variables' => 'MH-1 (mh_screening_results)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 37, 'code' => 'AHP037', 'key' => 'mh_managed',        'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Referred/managed for MH',                 'definition' => 'Unique adolescents referred and/or managed after MH screening.', 'variables' => 'MH-2 (mh_management_outcome)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 38, 'code' => 'AHP038', 'key' => 'su_screened',       'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for substance use',              'definition' => 'MH screenings in which the substance-use question was answered.', 'variables' => 'MH-0 (mh_screening_tools)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'Substance screening is a component of the MH tool, per the kpq matrix.', 'no_period' => true],
        ['id' => 39, 'code' => 'AHP039', 'key' => 'su_positive',       'group' => 'mh',      'level' => 'Outcome', 'type' => 'count',   'status' => 'active', 'label' => 'Screening positive for substance use',    'definition' => 'Unique adolescents with substance use identified.', 'variables' => 'MH-3 (mh_substance_identified)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null, 'no_period' => true],
        ['id' => 40, 'code' => 'AHP040', 'key' => 'su_managed',        'group' => 'mh',      'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Referred/managed for substance use',      'definition' => 'Substance-positive adolescents with any MH management outcome.', 'variables' => 'N/A in matrix', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'The kpq matrix lists no definition (N/A); documented proxy applied.', 'no_period' => true],

        ['id' => 41, 'code' => 'AHP041', 'key' => 'sti_screened',      'group' => 'sti',     'level' => 'Output',  'type' => 'count',   'status' => 'active', 'label' => 'Screened for STIs',                       'definition' => 'Unique adolescents who accessed the STI register in the period.', 'variables' => 'STI-S (sti_access)', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => null],
        ['id' => 42, 'code' => 'AHP042', 'key' => 'sti_treated',       'group' => 'sti',     'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Treated for STIs',                        'definition' => 'Unique adolescents recorded as treated in the STI register in the period.', 'variables' => 'N/A in matrix', 'disaggregation' => ['age', 'sex', 'facility', 'district'], 'note' => 'The kpq matrix lists no definition (N/A); documented proxy (sti_patient_treated) applied.'],

        ['id' => 43, 'code' => 'AHP043', 'key' => 'peer_sessions',     'group' => 'peer',    'level' => 'Output',  'type' => 'sum',     'status' => 'active', 'label' => 'Peer-led sessions conducted',             'definition' => 'Sum of peer-led sessions recorded in the period.', 'variables' => null, 'disaggregation' => ['facility', 'district'], 'note' => null],
        ['id' => 44, 'code' => 'AHP044', 'key' => 'peer_reached',      'group' => 'peer',    'level' => 'Output',  'type' => 'sum',     'status' => 'active', 'label' => 'Adolescents reached via peer activities', 'definition' => 'Sum of adolescents recorded as reached in the period.', 'variables' => null, 'disaggregation' => ['facility', 'district'], 'note' => null],
        ['id' => 45, 'code' => 'AHP045', 'key' => 'support_groups',    'group' => 'peer',    'level' => 'Output',  'type' => 'count',   'status' => 'proxy',  'label' => 'Adolescent support groups conducted',     'definition' => 'Register entries recording a support group conducted in the period.', 'variables' => null, 'disaggregation' => ['facility', 'district'], 'note' => 'Only a yes/no field exists, no meeting count.'],
    ],
];
